$(document).ready(function () {
        var twettear = [
        "Hay una fuerza motriz más poderosa que el vapor, la electricidad y la energía atómica: la voluntad"
  , "Primero tienes que aprender las reglas del juego, y después jugar mejor que nadie"
  , "El primer paso de la ignorancia es presumir de saber"
  , "El más poderoso hechizo para ser amado es amar."
  , "Errar es humano, pero más lo es culpar de ello a otros"
  , "El que confía sus secretos a otro hombre se hace esclavo de él"
  , "Dime y lo olvido, enséñame y lo recuerdo, involúcrame y lo aprendo"
  , "Quien tiene paciencia, obtendrá lo que desea"
  , "No malgastes tu tiempo, pues de esa materia está formada la vida"
  , "No cambies la salud por la riqueza, ni la libertad por el poder"
  , "Incluso la paz se puede comprar a un precio demasiado alto"
  , "Esta bien celebrar el éxito pero es más importante atender a las lecciones del fracaso."
  , "El éxito es un mal maestro."
  , "Seduce a la gente inteligente a pensar que no pueden perder."
  , "Todo hombre tiene derecho a decidir su propio destino"
  , "No te preocupes por una cosa, concéntrate en que las pequeñas cosas salgan bien."
  , "Nadie excepto nosotros mismos puede liberar nuestra mente."
  , "Si te sientes deprimido todos los días, estas diciendo oraciones al diablo."
  , "La salud es el regalo más grande, la satisfacción de la mayor riqueza, la fidelidad de la mejor relación."
  , "A un loco se le conoce por sus actos, a un sabio también."
  , "Cuida el exterior tanto como el interior; porque todo es uno."
  , "La reflexión es el camino hacia la inmortalidad; la falta de reflexión, el camino hacia la muerte"
  , "No insistas en el pasado, no sueñes en el futuro, concentra tu mente en el momento presente."
  , "La verdad se corrompe tanto con la mentira como con el silencio."
  , "Los hombres son como los vinos: la edad agria los malos y mejora los buenos."
  , "Cuanto mayor es la dificultad, mayor es la gloria."
  , "A pesar de que ya soy mayor, sigo aprendiendo de mis discípulos."
  , "Mi conciencia tiene en mí más peso que la opinión de todo el mundo."
  , "Exígete mucho a ti mismo y espera poco de los demás. Así te ahorrarás disgustos."
  , "Cada cosa tiene su belleza, pero no todos pueden verla."
  , "Donde hay educación no hay distinción de clases."
  , "Estudia el pasado si quieres predecir el futuro."
  , "El hombre que ha cometido un error y no lo corrige comete otro error mayor."
  , "Nadie te puede hacer sentir inferior sin tu consentimiento."
  , "Las grandes mentes discuten las ideas; las mentes promedio discuten los acontecimientos; las mentes pequeñas discuten con las personas."
  , "La confianza en sí mismo es el primer secreto del éxito."
  , "Grabad esto en vuestro corazón: cada día es el mejor del año."
  , "Todo hombre es sincero a solas; en cuanto aparece una segunda persona empieza la hipocresía."
  , "Un amigo es una persona con la que se puede pensar en voz alta."
  , "Los años enseñan muchas cosas que los días jamás llegan a conocer."
  , "La amistad duplica las alegrías y divide las angustias por la mitad."
  , "Vengándose, uno se iguala a su enemigo; perdonándolo, se muestra superior a él."
  , "La ocasión hay que crearla, no esperar a que llegue."
  , "Un hombre está dispuesto a creer aquello que le gustaría que fuera cierto."
  , "Lo que me preocupa no es que me hayas mentido, sino que, de ahora en adelante, y no podré creer en ti."
  , "La madurez del hombre es haber vuelto a encontrar la seriedad con la que jugaba cuando era niño."
  , "El destino de los hombres no está hecho de momentos felices, toda la vida los tiene, sino no de épocas felices."
  , "Ser independiente es cosa de una pequeña minoría, es el privilegio de los fuertes."
  , "Lo que no me mata, me hace más fuerte."
  , "En la vida no se trata de encontrarse uno mismo, sino de crearse uno mísmo."
  , "Dad al hombre salud y metas a alcanzar y no se detendrá a pensar sobre si es o no feliz."
  , "El miedo puede llevar a los hombres a cualquier extremo."
  , "Lo peor que puede pasarle aun hombre es llegar a pensar mal de sí mismo."
  , "No basta saber, se debe también aplicar. No es suficiente querer, se debe también hacer."
  , "El amor y el deseo son las alas del espíritu de las grandes hazañas."
  , "Muchos hombres no se equivocan jamás porque no se proponen nada razonable."
  , "Cuando el hombre no se encuentra a sí mismo, no encuentra nada."
  , "Hay una forma de saber si un hombre es honesto; pregúntaselo.Si dice que si, sabrás que es un sinverguenza."
  , "A parte del perro, un libro es el mejor amigo del hombre. Dentro de un perro esta demasiado oscuro para leer."
  , "El fracaso es simplemente una nueva oportunidad de empezar de nuevo, esta vez de forma más inteligente."
  , "No hay hombre vivo que no pueda hacer más de lo que el piensa que puede hacer."
  , "Los obstáculos son las cosas horribles que ves al apartar tus ojos de tu meta."
  , "Pensar es el trabajo más duro que hay, quizás por eso tan pocos se dedican a ello."
  , "La vida es lo que pasa mientras estas ocupado haciendo otros planes."
  , "La realidad deja mucho a la imaginación."
  , "Uno nunca tiene miedo de lo desconocido; uno tiene miedo de lo conocido llegando a un fin."
  , "La medida de la salud no es estar adaptado a una sociedad profundamente enferma."
  , "La habilidad de observar sin evaluar es la forma más alta de inteligencia."
  , "Dime a qué prestas atención y te diré quien eres."
  , "He cometido el peor pecado que uno puede cometer. No he sido feliz."
  , "Hay que tener cuidado al elegir a los enemigos porque uno termina pareciéndose a ellos."
  , "La duda es uno de los nombres de la inteligencia."
  , "Hay derrotas que tienen más dignidad que la victoria."
  , "Uno no es lo que es por lo que escribe, sino por lo que ha leído."
  , "Vive como si fueras a morir mañana, aprende como si fueras a vivir para siempre."
  , "El débil nunca puede olvidar. Olvidar es un atributo del fuerte."
  , "Nadie me puede hacer daño sin mi permiso."
  , "La fuerza no viene de una capacidad física. Viene de una voluntad indomable."
  , "La felicidad es cuando lo que piensas, dices y haces están en harmonía."
  , "La violencia es el último refugio del incompetente."
  , "La vida es agradable. La muerte es pacífica. Es la transición la que es problemática."
  , "La suerte favorece solo a la mente preparada."
  , "Nunca dejes que tu sentido de la moralidad se interponga en el camino de hacer lo que es correcto."
  , "La simplicidad es la última sofisticación."
  , "Las decepciones más grandes que el hombre sufre son por sus propias opiniones."
  , "No puedes tener mayor dominio que sobre ti mismo."
  , "Al igual que el coraje pone en peligro la vida, el miedo la protege."
  , "Todo el mundo piensa en cambiar el mundo, pero nadie piensa en cambiarse a si mismo."
  , "Si hablas a un hombre en un idioma que entiende, llegarás a su cabeza. Si le hablas en su idioma, llegará a su corazón."
  , "Siempre parece imposible hasta que se realiza."
  , "Una buena cabeza y un buen corazón son siempre combinaciones formidables."
  , "La mejor venganza es ser diferente a quien causó el daño."
  , "Tienes poder en tu mente, no afuera. Se consciente de esto y encontrarás las fuerza."
  , "Cuando te encuentres a ti mismo al lado de la mayoría, es tiempo de parar y reflexionar."
  , "A nadie le va mal durante mucho tiempo sin que él mismo tenga la culpa."
  , "El que no esté seguro de su memoria debe abstenerse de mentir."
  , "El signo más cierto de la sabiduría es la serenidad constante."
  , "El hombre sabio no lo es en todas las cosas."
  , "No hay cosa de la que tenga tanto miedo como del miedo."
  , "La senda de la virtud es muy estrecha y el camino del vicio, ancho y espacioso."
  , "El que lee mucho y anda mucho, ve mucho y sabe mucho."
  , "Amistades que son ciertas nadie las puede turbar."
  , "Donde una puerta se cierra, otra se abre."
  , "Sea moderado tu sueño; que el que no madruga con el sol, no goza del día."
  , "La envidia es una declaración de inferioridad."
  , "Los sabios son los que buscan la sabiduría; los necios piensan haberla encontrado."
  , "El coraje no se puede simular: es una virtud que escapa a la hipocresía."
  , "Si no puedes hacer grandes cosas, haz pequeñas cosas de una forma grande."
  , "Piensa dos veces antes de hablar, porque tus palabras e influencia plantarán la semilla del éxito o fracaso en la mente del otro."
  , "El hombre que hace más de lo que se le paga, pronto se le pagará más de loque hace."
  , "A veces podemos pasarnos años sin vivir en absoluto, y de pronto toda nuestra vida se concentra en un solo instante."
  , "La única ventaja de jugar con fuego es que aprende uno a no quemarse."
  , "Que hablen de uno es espantoso. Pero hay algo peor: que no hablen."
  , "Las preguntas no son nunca indiscretas. Las respuestas, a veces sí."
  , "La pregunta real no es si la vida existe antes de la muerte. La pregunta real es si estas vivo antes de la muerte."
  , "La juventud no tiene edad."
  , "El que piensa que puede, puede. El que piensa que no puede, no puede. Esa es una inexorable e indiscutible ley."
  , "Toma mucho tiempo llegar a ser jóven."
  , "La mayor declaración de amor es la que no se hace; el hombre que siente mucho, habla poco."
  , "La libertad está en ser dueños de nuestra propia vida."
  , "Buscando el bien de nuestros semejantes, encontramos el nuestro."
  , "Cada minuto que estas cabreado pierdes sesenta segundos de felicidad."
  , "La paciencia es amarga, pero sus frutos son dulces."
  , "La juventud es el momento de estudiar la sabiduría; la vejez, el de practicarla."
  , "Si la razón hace al hombre, el sentimiento lo conduce."
  , "Siempre es más valioso tener el respeto que la admiración de las personas."
  , "Nadie puede ser feliz si no se aprecia a sí mismo."
  , "Importa mucho más lo que tú piensas de ti mismo que lo que los otros opinen de ti."
  , "Si quieres que tu secreto sea guardado, guárdalo tú mismo."
  , "No es pobre el que tiene poco, sino el que mucho desea."
  , "El lenguaje de la verdad debe ser, sin duda alguna, simple y sin artificios."
  , "La recompensa de una buena acción está en haberla hecho."
  , "La inteligencia es la habilidad de adaptarse al cambio."
  , "El trabajo te da significado y propósito y la vida esta vacía sin el."
  , "Puede ser un héroe el que triunfa y el que sucumbe, pero jamás el que abandona el combate."
  , "Para disipar una duda, cualquiera que sea, se necesita una acción."
  , "Siempre hay un lugar en las cumbres para el hombre valiente y que se esfuerza."
  , "El hablar que no termina en acción, mejor suprimirlo."
  , "Sólo en un mundo de hombres sinceros es posible la unión."
  , "Si hiciéramos las cosas de las que somos capaces, nos sorprenderíamos a nosotros literalmente."
  , "Los cuarenta son la edad madura de la juventud; los cincuenta la juventud de la edad madura."
  , "La melancolía es la felicidad de estar triste."
  , "Atreveos: el progreso solamente se logra así."
  , "A nadie le faltan fuerzas; lo que a muchísimos les falta es voluntad."
  , "El sufrir merece respeto, el someterse es despreciable."
  , "Las que conducen y arrastran al mundo no son las máquinas, sino las ideas."
  , "Sólo es inmensamente rico aquel que sabe limitar sus deseos."
  , "El verdadero valor consiste en saber sufrir."
  , "Ser bueno solamente consigo mismo es ser bueno para nada."
  , "Quienes creen que el dinero lo hace todo, terminan haciendo todo por dinero."
  , "Decimos una necedad y a fuerza de repetirla acabamos creyéndola."
  , "Cuanto más te gustas a ti mismo, menos te pareces a los demás, lo que te hace único."
  , "El modo de empezar es dejar de hablar y comenzar a hacer."
  , "Hay más tesoros en los libros que en todo el botín pirata de la isla del tesoro."
  , "Cuando eres curioso, encuentras muchas cosas interesantes que hacer."
  , "El riesgo viene de no saber qué estas haciendo."
  , "Solo compra cosas con las que estarías feliz si el mercado cerrase durante 10 años."
  , "Si cambias el modo en que miras las cosas, las cosas que miras cambian."
  , "Si no recuerdas la más ligera locura en que el amor te hizo caer, no has amado."
  , "Un hombre que no se alimenta de sus sueños envejece pronto."
  , "El destino es el que baraja las cartas, pero nosotros somos los que jugamos."
  , "No tratéis de guiar al que pretende elegir por sí su propio camino."
  , "Es mejor ser rey de tu silencio que esclavo de tus palabras."
  , "Una broma es algo muy serio."
  , "La actitud es una pequeña cosa que hace una gran diferencia."
  , "El precio de la grandeza es la responsabilidad."
  , "Hagas lo que hagas, bueno o malo, la gente siempre tendrá algo que decir."
  , "Llega el momento en que hay que darse cuenta que algunas personas pueden quedarse en nuestro corazón, pero no en nuestra vida."
  , " Hazlo ahora. A veces“ después” se convierte en“ nunca”."
  , "Demasiado ego matará a tu talento."
  , "La vida no es un problema a ser resuelto, sino una realidad a ser experimetada."
  , "La vida es realmente simple, pero insistimos en hacerla complicada."
  , "No recordamos días, recordamos momentos."
  , "Al final, no cuentan los años de tu vida.Cuenta la vida en tu años."
  , "Solo vives una vez, pero si lo haces bien, una vez es suficiente."
  , "La cosa más importante de la vida es disfrutarla, ser feliz, es todo lo que importa."
  , "El propósito de nuestra vida es ser feliz."
  , "La buena vida es inspirada por amor y guiada por el conocimiento."
  , "La vida es como montar en bicicleta.Para mantener el equilibrio debes seguir adelante."
  , "La vida es inherentemente arriesgada Solo hay un riesgo mayor que deberías evitar, y es el riesgo de no hacer nada."
  , "pic.twitter.com/INO24lXwTw"
  , "pic.twitter.com/jDih5iuGMM"
  , "pic.twitter.com/w5UKln0wpe"
  , "pic.twitter.com/XPhdfebLyM"
  , "pic.twitter.com/8BcOM2g5ZJ"
  , "pic.twitter.com/I9QTVbdOqZ"
  , "pic.twitter.com/7NvApWg1Xx"
  , "pic.twitter.com/dNa9oUzTYq"
  , "pic.twitter.com/X85JcXcIsg"
  , "pic.twitter.com/DMHX5C8wYz"
  , "pic.twitter.com/DMHX5C8wYz"
  , "pic.twitter.com/BN67VZIH4D"
  , "pic.twitter.com/6nJepMcBOi"
  , "pic.twitter.com/x8ZfgI64bF"
  , "pic.twitter.com/DzVOdHt3b8"
  , "pic.twitter.com/38sBxLPnLr"
  , "pic.twitter.com/38sBxLPnLr"
  , "pic.twitter.com/WeBmCZbBiF"
  , "pic.twitter.com/NNHFMZFhgF"
  , "pic.twitter.com/byNAbYskc9"
  , "pic.twitter.com/cklIl0gZiM"
  , "pic.twitter.com/QIv7zYZI5y"
  , "pic.twitter.com/QIv7zYZI5y"
  , "pic.twitter.com/JaK0Y6tLpf"
  , "pic.twitter.com/PH1JbYBTAN"
  , "pic.twitter.com/MOTjCJrGoz"
  , "pic.twitter.com/h1ypeUetj6"
  , "pic.twitter.com/s31HMWBC8D"
  , "pic.twitter.com/afKFIjHpQy"
  , "pic.twitter.com/dkv8UfaCUC"
  , "pic.twitter.com/nPnzL3YGcn"
  , "pic.twitter.com/1RXlJfBeEQ"
  , "pic.twitter.com/nPnzL3YGcn"
  , "pic.twitter.com/1RXlJfBeEQ"
  , "pic.twitter.com/gMMCV8mvbV"
  , "pic.twitter.com/DuoPGUF3Yu"
  , "pic.twitter.com/rEbsdgcYwk"
  , "pic.twitter.com/OR98PYCxj8"
  , "pic.twitter.com/0lyE5aT7r8"
  , "pic.twitter.com/0lyE5aT7r8"
  , "pic.twitter.com/CKjAagvEta"
  , "pic.twitter.com/rnmhOutyOS"
  , "pic.twitter.com/5zAm8E7uDP"
  , "pic.twitter.com/xIC7f4oPkU"
  , "pic.twitter.com/rUgaVpKgJy"
  , "pic.twitter.com/snlzuoglZ7"
  , "pic.twitter.com/O7rnFDoHQs"
  , "pic.twitter.com/u3wFzS4mlG"
  , "pic.twitter.com/l62KCqanid"
  , "pic.twitter.com/L2KYe6nhxg"
  , "pic.twitter.com/kIOlrsjjlw"
  , "pic.twitter.com/LkCLylGytO"
  , "pic.twitter.com/zZB0JTDXQs"
  , "pic.twitter.com/boVtvsW2ql"
  , "pic.twitter.com/3Awchy8Ozr"
  , "pic.twitter.com/dtFFy7rXbx"
  , "pic.twitter.com/f2VdsC5j3z"
  , "pic.twitter.com/f2VdsC5j3z"
  , "pic.twitter.com/l4CpZfFYY2"
  , "pic.twitter.com/XmiD5O7Amt"
  , "pic.twitter.com/vSAbHOVbS9"
  , "pic.twitter.com/bfZ890iK05"
  , "pic.twitter.com/iCLdufuQNj"
  , "pic.twitter.com/ffUeEqBzYx"
  , "pic.twitter.com/ENbVhDzVZi"
  , "pic.twitter.com/h4ZqqvY74v"
  , "pic.twitter.com/WyMx1sdLeY"
  , "pic.twitter.com/ilkA9yafJB"
  , "pic.twitter.com/QRFTzg9uBy"
  , "pic.twitter.com/jAwo1ZwTee"
  , "pic.twitter.com/fYlDM9IhWb"
  , "pic.twitter.com/FwlsaF5hhm"
  , "pic.twitter.com/h4TprUmdsW"
  , "pic.twitter.com/ciG4heqz2e"
  , "pic.twitter.com/xnG5Mmajxf"
  , "pic.twitter.com/hoSUMDgGMy"
  , "pic.twitter.com/3CpZaG7gUf"
  , "pic.twitter.com/83ogQgaJ2X"
  , "pic.twitter.com/iz27b2CPfs"
  , "pic.twitter.com/8Cj57hKxS0"
  , "pic.twitter.com/qp7tp4gXy9"
  , "pic.twitter.com/5bJgWsSk0C"
  , "pic.twitter.com/qjFXxMJS9U"
  , "pic.twitter.com/5wXJJlqVpj"
  , "pic.twitter.com/7hb3iIP9Bi"
  , "pic.twitter.com/catg0rAjgI"
  , "pic.twitter.com/IHmwzxLsj2"
  , "pic.twitter.com/mKo0wxyYqV"
  , "pic.twitter.com/SjzbRpB0Ek"
  , "pic.twitter.com/SZIkFvLFHF"
  , "pic.twitter.com/gxcPaEaFqG"
  , "pic.twitter.com/NpUZsJmYw3"
  , "pic.twitter.com/bKLMxKupp5"
  , "pic.twitter.com/N6R12WgUZx"
  , "pic.twitter.com/2IFNpjbop6"
  , "pic.twitter.com/8Csd8NZnf5"
  , "pic.twitter.com/aWBhI0FhG0"
  , "pic.twitter.com/lk6QL9bF7R"
  , "pic.twitter.com/0IrrqZS6aD"
  , "pic.twitter.com/in00OTXqDz"
  , "pic.twitter.com/9iYCGpBdfT"
  , "pic.twitter.com/C9FwHdaKDp"
  , "pic.twitter.com/umVIgViFao"
  , "pic.twitter.com/SsmQUoAkg3"
  , "pic.twitter.com/QCE0I8v0To"
  , "pic.twitter.com/KUcLywjUjj"
  , "pic.twitter.com/YJOvKTLgkL"
  , "pic.twitter.com/YPD9io5Tvz"
  , "pic.twitter.com/f64LufzeO8"
  , "pic.twitter.com/5JLF0lfPOP"
  , "pic.twitter.com/wceFa0uPv7"
  , "pic.twitter.com/Omi6zxsTj9"
  , "pic.twitter.com/vUqWqZGzqm"
  , "pic.twitter.com/hGd8v1qHgH"
  , "pic.twitter.com/Xjyl2lgw7A"
  , "pic.twitter.com/0U4qihgJhj"
  , "pic.twitter.com/GTYspWihIk"
  , "pic.twitter.com/1IXp6PmEld"
  , "pic.twitter.com/m0qec1AZC3"
  , "pic.twitter.com/iFLACG3XFc"
  , "pic.twitter.com/pT7DP9vlYY"
  , "pic.twitter.com/e0vPfZf1gO"
  , "pic.twitter.com/UgHoBehFJt"
  , "pic.twitter.com/Mo7fsDVEWV"
  , "pic.twitter.com/CvBBtcWDgy"
  , "pic.twitter.com/FwkFEMX3f5"
  , "pic.twitter.com/OFnxrTS7mM"
  , "pic.twitter.com/8HfdL7EWIB"
  , "pic.twitter.com/y305Fg9QAd"
  , "pic.twitter.com/76U5IdBUWD"
  , "pic.twitter.com/lntCI15ZH6"
  , "pic.twitter.com/crnK1kQiWC"
  , "pic.twitter.com/LVPkdGRoz0"
  , "pic.twitter.com/qLhKHuSmNT"
  , "pic.twitter.com/Y7faWhNP4L"
  , "pic.twitter.com/qx2m7tza9Z"
  , "pic.twitter.com/toy1IhUr4x"
  , "pic.twitter.com/jQEKt62nyF"
  , "pic.twitter.com/5hKkBLjy2N"
  , "pic.twitter.com/ehI1xmxFm9"
  , "pic.twitter.com/GtqKMXoeo1"
  , "pic.twitter.com/pL9a8hYkRx"
  , "pic.twitter.com/9DopLVD0La"
  , "pic.twitter.com/6zKt4dAw5O"
  , "pic.twitter.com/qyIai18QIH"
  , "pic.twitter.com/sYhMH8vbsE"
  , "pic.twitter.com/z0Lfr9ZQLe"
  , "pic.twitter.com/adEfnBvq0E"
  , "pic.twitter.com/4y3s4mGzSo"
  , "pic.twitter.com/fLK0ZozWQJ"
  , "pic.twitter.com/k3Ir5zMCvQ"
  , "pic.twitter.com/V9IaBQiJS5"
  , "pic.twitter.com/kPvEVAAOsc"
  , "pic.twitter.com/8QqxDzIRu9"
  , "pic.twitter.com/ePIwjaYRT1"
  , "pic.twitter.com/DCxBwLDktl"
  , "pic.twitter.com/5BfzALlWoj"
  , "pic.twitter.com/mudmXf8JnW"
  , "pic.twitter.com/f3PIgYKlMa"
  , "pic.twitter.com/bEylo3ux8k"
  , "pic.twitter.com/KizhoGjngd"
  , "pic.twitter.com/g3nCaKP8Jb"
  , "pic.twitter.com/gW2PM9BO0e"
  , "pic.twitter.com/7ABM7FP42s"
  , "pic.twitter.com/a8YhQWRzf9"
  , "pic.twitter.com/01rYlueXzC"
  , "pic.twitter.com/WSMa1krcDc"
  , "pic.twitter.com/4vk1G6tQbv"
  , "pic.twitter.com/MRMzhJm2pm"
  , "pic.twitter.com/fCa9mPEQcW"
  , "pic.twitter.com/op40OOFqC3"
  , "pic.twitter.com/jxQcCcn70E"
  , "pic.twitter.com/tNhjMYZTtA"
  , "pic.twitter.com/HDBLOjDbXZ"
  , "pic.twitter.com/nMaZC9mKE5"
  , "pic.twitter.com/6UIaX3KGak"
  , "pic.twitter.com/BnehYHSM2v"
  , "pic.twitter.com/Pz1HiD7OMO"
  , "pic.twitter.com/OEx9Yrlp0m"
  , "pic.twitter.com/79y29c4k6p"
  , "pic.twitter.com/NvHe84UL8L"
  , "pic.twitter.com/CiC96O34FT"
  , "pic.twitter.com/MY8IxQYdzH"
  , "pic.twitter.com/OhLAXF5yHG"
  , "pic.twitter.com/M4ShPuIbvI"
  , "pic.twitter.com/OEIwiWSAEs"
  , "pic.twitter.com/7TabYXT9F9"
  , "pic.twitter.com/p2tn97CT9G"
  , "pic.twitter.com/MjtLkE02uT"
  , "pic.twitter.com/d0pYhqsmni"
  , "pic.twitter.com/0jtfWXmtnO"
  , "pic.twitter.com/RD4NLDd0wz"
  , "pic.twitter.com/1Jasysg6Jd"
  , "pic.twitter.com/mHsP37oVma"
  , "pic.twitter.com/zyLz9RctbM"
  , "pic.twitter.com/1YdfQ7MNot"
  , "pic.twitter.com/Dapgq8fRYP"
  , "pic.twitter.com/Y0JfwbgqtK"
  , "pic.twitter.com/hrUhtgFUul"
  , "pic.twitter.com/t0NwAvUA1v"
  , "pic.twitter.com/yGodC1zopj"
  , "pic.twitter.com/qF7jciXPNq"
  , "pic.twitter.com/CTKmMKZT4W"
  , "pic.twitter.com/5J7ybyqUMI"
  , "pic.twitter.com/65NAYVxQGu"
  , "pic.twitter.com/KYmi3vCWZD"
  , "pic.twitter.com/cn36TbyVNL"
  , "pic.twitter.com/BLFB6HRuBC"
  , "pic.twitter.com/PCIoZ34JK1"
  , "pic.twitter.com/xHVZ36ZNCX"
  , "pic.twitter.com/X80sFfPZCj"
  , "pic.twitter.com/31z5sEutYW"
  , "pic.twitter.com/8LSRnMpa7G"
  , "pic.twitter.com/hCeowPXNLd"
  , "pic.twitter.com/IwKzu8TVl5"
  , "pic.twitter.com/MqZiqJ76AJ"
  , "pic.twitter.com/Ptt5gJFzmb"
  , "pic.twitter.com/NQRm0mDktF"
  , "pic.twitter.com/BvwIFpOF7A"
  , "pic.twitter.com/IoH9bi7wC8"
  , "pic.twitter.com/udIjDpQUIm"
  , "pic.twitter.com/u1MU7zTNIl"
  , "pic.twitter.com/W5M5nuGe3g"
  , "pic.twitter.com/VLIrNyW9nc"
  , "pic.twitter.com/7O0BP6m5Wl"
  , "pic.twitter.com/VUnJX3KgHO"
  , "pic.twitter.com/JW4T9l7kkJ"
  , "pic.twitter.com/lhpY641cqu"
  , "pic.twitter.com/QUEovOvpU3"
  , "pic.twitter.com/wC9GCSs8sz"
  , "pic.twitter.com/ckf3YAioq2"
  , "pic.twitter.com/D0suVlMWr9"
  , "pic.twitter.com/WKFJWD8myM"
  , "pic.twitter.com/AQe1gIYI1S"
  , "pic.twitter.com/gzmWLqphrJ"
  , "pic.twitter.com/uBPmIZ0Hpd"
  , "pic.twitter.com/zHdBRBXeqF"
  , "pic.twitter.com/Qkhh7KeKe8"
  , "pic.twitter.com/d2UNwjG0hN"
  , "pic.twitter.com/iAzaxvhpFq"
  , "pic.twitter.com/ZA7YGB56Do"
  , "pic.twitter.com/ydTRrQOh8h"
  , "pic.twitter.com/x7xQ3pIgkz"
  , "pic.twitter.com/MJiAz2Iy0f"
  , "pic.twitter.com/83kG2TYorZ"
  , "pic.twitter.com/Tk5RDVsEog"
  , "pic.twitter.com/cMLOa6QtmI"
  , "pic.twitter.com/1YW1MyJj5p"
  , "pic.twitter.com/QrUOaMrL2N"
  , "pic.twitter.com/UjPkPrKvoo"
  , "pic.twitter.com/QiIFC1YIUc"
  , "pic.twitter.com/mMVbKoc5yX"
  , "pic.twitter.com/DYmhy8Fx9k"
  , "pic.twitter.com/bfN2MbD5cT"
  , "pic.twitter.com/8jom31ZiJh"
  , "pic.twitter.com/wAsBDwfL2y"
  , "pic.twitter.com/kYyN8pALdD"
  , "pic.twitter.com/WquZrth18V"
  , "pic.twitter.com/9carxvIi5S"
  , "pic.twitter.com/xEVxlLLtve"
  , "pic.twitter.com/Mm4SvIfMMS"
  , "pic.twitter.com/D9eD7nsbMp"
  , "pic.twitter.com/XxvEjJ1iNl"
  , "pic.twitter.com/QxwbeYH7r2"
  , "pic.twitter.com/22ulymdkCT"
  , "pic.twitter.com/TxofLN8Zvz"
  , "pic.twitter.com/9OKfAayG4P"
  , "pic.twitter.com/VEFllz99yC"
  , "pic.twitter.com/rDsLLigpI5"
  , "pic.twitter.com/NPYRNg05ln"
  , "pic.twitter.com/0k9rQeGli1"
  , "pic.twitter.com/LNzYeoDu18"
  , "pic.twitter.com/llxvy3BZmo"
  , "pic.twitter.com/GPerNts57U"
  , "pic.twitter.com/sMZxlA1WoG"
  , "pic.twitter.com/4fownmW6AZ"
  , "pic.twitter.com/L4kfeRRJKV"
  , "pic.twitter.com/QQOGgbRt6m"
  , "pic.twitter.com/RJSqzkOM29"
  , "pic.twitter.com/phnwTwTOxI"
  , "pic.twitter.com/4Gy4yHRSVp"
  , "pic.twitter.com/CJWMo6H5tB"
  , "pic.twitter.com/wqf4Qcnvcz"
  , "pic.twitter.com/T6ZubDf1Qn"
  , "pic.twitter.com/Isw60IzI4n"
  , "pic.twitter.com/AFAAQyOY7N"
  , "pic.twitter.com/y9K8XTNERN"
  , "pic.twitter.com/baGEElG7JI"
  , "pic.twitter.com/SqKJXIQWGT"
  , "pic.twitter.com/N2MDhqQxoT"
  , "pic.twitter.com/zqkvqIDicA"
  , "pic.twitter.com/ILD7FF26ti"
  , "pic.twitter.com/xSvY7gTInp"
  , "pic.twitter.com/agh1Y2VFvW"
  , "pic.twitter.com/DLZEyhVEc5"
  , "pic.twitter.com/6tJawOLU1d"
  , "pic.twitter.com/o3xpn7lwV8"
  , "pic.twitter.com/9qQ7pdXnn5"
  , "pic.twitter.com/Y8NO2j4mPx"
  , "pic.twitter.com/tW3CxgD729"
  , "pic.twitter.com/LmLcAfK8lM"
  , "pic.twitter.com/p19ziKib0R"
  , "pic.twitter.com/ImMjuerETz"
  , "pic.twitter.com/lyiW2230UG"
  , "pic.twitter.com/5qP1HsnMEn"
  , "pic.twitter.com/SQcf2PhhQr"
  , "pic.twitter.com/ihTecB3mSj"
  , "pic.twitter.com/vOyp67FxeM"
  , "pic.twitter.com/8FC9PJoQ0C"
  , "pic.twitter.com/XgDXHqnbTk"
  , "pic.twitter.com/lXvGAR3He9"
  , "pic.twitter.com/UYRRqZNegG"
  , "pic.twitter.com/JPNhi7bnyN"
  , "pic.twitter.com/ck0MMIzNKE"
  , "pic.twitter.com/cZJfxN0o5c"
  , "pic.twitter.com/E43WqHywDM"
  , "pic.twitter.com/uytE1Lx2Ms"
  , "pic.twitter.com/JjC4UKvHcW"
  , "pic.twitter.com/8JgTLOeeWH"
  , "pic.twitter.com/DWinBLtxZ5"
  , "pic.twitter.com/3DjiIK8TMy"
  , "pic.twitter.com/qWXjKchA0V"
  , "pic.twitter.com/hZUBgaUVtI"
  , "pic.twitter.com/ZxeU18XZDy"
  , "pic.twitter.com/U2e5L0b0MD"
  , "pic.twitter.com/ejnS5secK1"
  , "pic.twitter.com/hlmouPGCKz"
  , "pic.twitter.com/46u8IrC6jE"
  , "pic.twitter.com/nh80bKv8tV"
  , "pic.twitter.com/p5jajec68u"
  , "pic.twitter.com/za5GRpLPBn"
  , "pic.twitter.com/KLLwbnWcp5"
  , "pic.twitter.com/dhP0n65FYF"
  , "pic.twitter.com/KKowAwwg95"
  , "pic.twitter.com/SPsRiKQk69"
  , "pic.twitter.com/asy7tYby3c"
  , "pic.twitter.com/Bf6wPR2rY6"
  , "pic.twitter.com/gqSn7VS96T"
  , "pic.twitter.com/atiPddLm8E"
  , "pic.twitter.com/WekIhkPhH1"
  , "pic.twitter.com/CU6yfzPwGb"
  , "pic.twitter.com/ck8O0Fbl4c"
  , "pic.twitter.com/yR80zxmqxi"
  , "pic.twitter.com/t0XiR8N01l"
  , "pic.twitter.com/WY3tl2lj6y"
  , "pic.twitter.com/lHS7lINrbJ"
  , "pic.twitter.com/rEZTGSOtvt"
  , "pic.twitter.com/1iMYciSPGA"
  , "pic.twitter.com/CH6vUqmmfT"
  , "pic.twitter.com/UszTzboZbU"
  , "pic.twitter.com/WetTndDXBB"
  , "pic.twitter.com/MGWKg9noMd"
  , "pic.twitter.com/PVB9QCz5mG"
  , "pic.twitter.com/ookROz6lIb"
  , "pic.twitter.com/SjpL72ndVM"
  , "pic.twitter.com/zJfapnaPm9"
  , "pic.twitter.com/OnP9u2GBOs"
  , "pic.twitter.com/2ePV6t2kfO"
  , "pic.twitter.com/m8ijNdCpTd"
  , "pic.twitter.com/x2ItyfS8rK"
  , "pic.twitter.com/e0dFbsuq97"
  , "pic.twitter.com/qd5iNkLnWd"
  , "pic.twitter.com/DSAi8GY0Ws"
  , "pic.twitter.com/2IiY7XCj6L"
  , "pic.twitter.com/AVYZXTMuFr"
  , "pic.twitter.com/02DvcbSKO4"
  , "pic.twitter.com/9rdM8S6HNU"
  , "pic.twitter.com/JlFagNkIbV"
  , "pic.twitter.com/u4oZKIS8fu"
  , "pic.twitter.com/vMmcMmK6lb"
  , "pic.twitter.com/JP2uuY90HM"
  , "pic.twitter.com/ggJAApeVcN"
  , "pic.twitter.com/5kWhaLT8Xd"
  , "pic.twitter.com/uXHcOAwwhE"
  , "pic.twitter.com/kGskMbuZRl"
  , "pic.twitter.com/Jb1AJIkO0U"
  , "pic.twitter.com/IPtRdkSYKv"
  , "pic.twitter.com/HEMe6uor9Y"
  , "pic.twitter.com/pXOzkJq7QQ"
            , "pic.twitter.com/ANrZMBvf4N"
, "pic.twitter.com/y1MkWkT3vv"
, "pic.twitter.com/cuJqYHLymg"
, "pic.twitter.com/rRyrfqmjZ2"
, "pic.twitter.com/TvK6gMHJ54"
, "pic.twitter.com/85L8UZcnB2"
, "pic.twitter.com/RjlYJAGhgm"
, "pic.twitter.com/ABXrzaY22g"
, "pic.twitter.com/OzzLHgWOgY"
, "pic.twitter.com/GmzCPbilZ8"
, "pic.twitter.com/9hF5DWanGG"
, "pic.twitter.com/3lU8VqEdky"
, "pic.twitter.com/9GsSlZdfqi"
, "pic.twitter.com/HKXe0q3xr3"
, "pic.twitter.com/CyvwZ5Auc4"
, "pic.twitter.com/SVq3EgGoiD"
, "pic.twitter.com/QVcm8kLdi0"
, "pic.twitter.com/49UuUHn2qz"
, "pic.twitter.com/HQTNYmA0oy"
, "pic.twitter.com/0dCDfqxH8N"
, "pic.twitter.com/NU6vTkXWJS"
, "pic.twitter.com/b4oWupbdaz"
, "pic.twitter.com/VfUTjG6MIK"
, "pic.twitter.com/c4vfXkTmoq"
, "pic.twitter.com/lVkERRn7ks"
, "pic.twitter.com/HFKkbKbLnX"
, "pic.twitter.com/MRlJjMyXSb"
, "pic.twitter.com/ZFrCu826wq"
, "pic.twitter.com/K8nDbLPMVX"
, "pic.twitter.com/kbT5AtgItG"
, "pic.twitter.com/kWe5HtJDBB"
, "pic.twitter.com/RuRHfDGqCv"
, "pic.twitter.com/kSA3SUmevC"
, "pic.twitter.com/6ahPdyh8JX"
, "pic.twitter.com/1WPdXbrS7p"
, "pic.twitter.com/RgyB6paV1y"
, "pic.twitter.com/qPSuIxUsWR"
, "pic.twitter.com/6CjUbiDSd6"
, "pic.twitter.com/Hbh5K6IlJ2"
, "pic.twitter.com/ddEuPLsJAx"
, "pic.twitter.com/7rvn4wFNGa"
, "pic.twitter.com/Y5iKgn5aTN"
, "pic.twitter.com/aBzX30ibxW"
, "pic.twitter.com/SZkfvIhR91"
, "pic.twitter.com/K7Xlki2J6Z"
, "pic.twitter.com/5WJEyYkZHx"
, "pic.twitter.com/NcRduMO7XR"
, "pic.twitter.com/MKpSD0E60g"
, "pic.twitter.com/kTiZUMLpyf"
, "pic.twitter.com/NDh9C8O9E6"
, "pic.twitter.com/L8HOGToeeh"
, "pic.twitter.com/JuJa2gnCRj"
, "pic.twitter.com/altqGV8hds"
, "pic.twitter.com/2XDPlzVh2O"
, "pic.twitter.com/vDpRNrfUrK"
, "pic.twitter.com/mZzZesuxbc"
, "pic.twitter.com/Ak2QgX03Qu"
, "pic.twitter.com/JKoO17GbH1"
, "pic.twitter.com/Krc7x1dcCz"
, "pic.twitter.com/mRui9nB8l4"
, "pic.twitter.com/4nQFhr8Vau"
, "pic.twitter.com/IWoUZ3aJya"
, "pic.twitter.com/1kqCwSkiTf"
, "pic.twitter.com/YSkz2KZ9i4"
, "pic.twitter.com/yXhORMyZ1H"
, "pic.twitter.com/5sti2OyjHu"
, "pic.twitter.com/uhv9whGmwj"
, "pic.twitter.com/m2HGL3j7ng"
, "pic.twitter.com/5i7nxtLAfR"
, "pic.twitter.com/xkxEvnQXci"
, "pic.twitter.com/J1jCeBMROl"
, "pic.twitter.com/tA26urCZwk"
, "pic.twitter.com/xu4pLXfxZn"
, "pic.twitter.com/JwalyLWQWm"
, "pic.twitter.com/VkzK1EiBes"
, "pic.twitter.com/rkXQxI8zVo"
, "pic.twitter.com/w1tcwYOih3"
, "pic.twitter.com/NFFAzuvqkM"
, "pic.twitter.com/Xe4ujXlCHI"
, "pic.twitter.com/GqJM619MYG"
, "pic.twitter.com/s2uWZZbzR8"
, "pic.twitter.com/wsi8XcLaae"
, "pic.twitter.com/FD1Br1S5E4"
, "pic.twitter.com/jczwCK4XXf"
, "pic.twitter.com/kH8SSwnDRt"
, "pic.twitter.com/Ui6sxfPFeR"
, "pic.twitter.com/By2CJx7Z67"
, "pic.twitter.com/aIeFYj3iZp"
, "pic.twitter.com/0uGW6GTgZV"
, "pic.twitter.com/NK6KjMaS3G"
, "pic.twitter.com/Yg7e8Elo2f"
, "pic.twitter.com/HjzDKOBCRU"
, "pic.twitter.com/tPj0Y1msgY"
, "pic.twitter.com/l7Bnt3QR7S"
, "pic.twitter.com/k6k0gAJNFa"
, "pic.twitter.com/7ypBl7hmeE"
, "pic.twitter.com/LNgFH3v8yq"
, "pic.twitter.com/HJ2UVPROav"
, "pic.twitter.com/xvCuWv5yxs"
, "pic.twitter.com/siee2SWACV"
, "pic.twitter.com/qeSGemlQiT"
, "pic.twitter.com/SLUGhtYPUf"
, "pic.twitter.com/nnVrq8LFoL"
, "pic.twitter.com/6sGsQSJHp3"
, "pic.twitter.com/Xykf2XeSPW"
, "pic.twitter.com/MhpRnDYpcg"
, "pic.twitter.com/ukHx4uQC4P"
, "pic.twitter.com/3B4N2J6jTA"
, "pic.twitter.com/LDfYV1c757"
, "pic.twitter.com/em2LKObLob"
, "pic.twitter.com/uoEaoor6P8"
, "pic.twitter.com/yiKhBUJGzC"
, "pic.twitter.com/H0TRgGpOXF"
, "pic.twitter.com/imvYCkYk2w"
, "pic.twitter.com/iQe4JWEkne"
, "pic.twitter.com/fhi22DLZ6E"
, "pic.twitter.com/U4mLHOkPpO"
, "pic.twitter.com/fHrHAYkRkn"
, "pic.twitter.com/WRVqmN6pVB"
, "pic.twitter.com/fGoAAN9rOi"
, "pic.twitter.com/97Ywz5YztI"
, "pic.twitter.com/eYueBgxOsg"
, "pic.twitter.com/u0C39GM7rP"
, "pic.twitter.com/Fece5vnmuW"
, "pic.twitter.com/zuBVBcyxn9"
, "pic.twitter.com/lWTuydVznH"
, "pic.twitter.com/G5Puy16Loj"
, "pic.twitter.com/vFGO5fW8F7"
, "pic.twitter.com/sH9tYbVl2B"
, "pic.twitter.com/IGiiu98LEI"
, "pic.twitter.com/tmRpGJGDD8"
, "pic.twitter.com/2B5MvXtAQq"
, "pic.twitter.com/ALoYhelwGd"
, "pic.twitter.com/IagGzRZNAc"
, "pic.twitter.com/3EfwoqBfgP"
, "pic.twitter.com/CfeqLxj9Lo"
, "pic.twitter.com/3QXr7kSFCE"
, "pic.twitter.com/ECioFUUpHU"
, "pic.twitter.com/GbJGl5Q4zz"
, "pic.twitter.com/qchszEJXv5"
, "pic.twitter.com/0M3m7eaee1"
, "pic.twitter.com/lSrYHjtOyg"
, "pic.twitter.com/0Pt0Q3w14j"
, "pic.twitter.com/ex3SyFGlbX"
, "pic.twitter.com/5vgZj00NUR"
, "pic.twitter.com/jhrxbjLRDP"
, "pic.twitter.com/aRgv0dUzx7"
, "pic.twitter.com/KkVwL8qrzA"
, "pic.twitter.com/eqAoxZQ0f3"
, "pic.twitter.com/iblMrwg96M"
, "pic.twitter.com/nNw5o4tbXR"
, "pic.twitter.com/31d86G9VA0"
, "pic.twitter.com/zFsbMU3K8D"
, "pic.twitter.com/EhV0NxZ2Xm"
, "pic.twitter.com/FkWMH10xNB"
, "pic.twitter.com/VDEKR0qJu7"
, "pic.twitter.com/uQpF2OIlid"
, "pic.twitter.com/7s9UQv22dq"
, "pic.twitter.com/O6eSQMGkOk"
, "pic.twitter.com/VV39em6Typ"
, "pic.twitter.com/6xLfXx70Xk"
, "pic.twitter.com/KoLDWbIMyg"
, "pic.twitter.com/FuOq9kukw2"
, "pic.twitter.com/lKHTxe762H"
, "pic.twitter.com/UjzoxPfwny"
, "pic.twitter.com/uYKYHVtGt7"
, "pic.twitter.com/PGxrRtign4"
, "pic.twitter.com/BjlNRH6TZ3"
, "pic.twitter.com/1cNZtnXAkw"
, "pic.twitter.com/vhM2IZ2bmA"
, "pic.twitter.com/yy78AwosXz"
, "pic.twitter.com/ousXh9R2yV"
, "pic.twitter.com/sq6M9VB6Ip"
, "pic.twitter.com/0B9H0PrrZi"
, "pic.twitter.com/sCO85Nm2xo"
, "pic.twitter.com/7xOnt7uMeI"
, "pic.twitter.com/g38t1Qf3Zf"
, "pic.twitter.com/AiroRKaoha"
, "pic.twitter.com/VNPnG4zBJx"
, "pic.twitter.com/F5pXwd2wNL"
, "pic.twitter.com/2dIG2uItAf"
, "pic.twitter.com/AdSYhnt8cq"
, "pic.twitter.com/1ncq7IxeWk"
, "pic.twitter.com/zzTF6WZDsO"
, "pic.twitter.com/faqZ2CkOFX"
, "pic.twitter.com/S91p8mil4Q"
, "pic.twitter.com/8BFQXnBXnX"
, "pic.twitter.com/peDomi79OL"
, "pic.twitter.com/6owixKWB87"
, "pic.twitter.com/omtL01V8mL"
, "pic.twitter.com/vyCs9Ol3aP"
, "pic.twitter.com/6nYgtPRuzR"
, "pic.twitter.com/YS09Vq98bP"
, "pic.twitter.com/zCdTIunDdh"
, "pic.twitter.com/24UJIH7m66"
, "pic.twitter.com/QlbBWNYqwi"
, "pic.twitter.com/wy3xVHx64I"
, "pic.twitter.com/Xu4scoCYHm"
, "pic.twitter.com/GgKvLhIs98"
, "pic.twitter.com/uBZ2nJcRra"
, "pic.twitter.com/eP4DcJIqRa"
, "pic.twitter.com/5T5UloX3oB"
, "pic.twitter.com/XGfz8neoos"
, "pic.twitter.com/YsRGUGsE8U"
, "pic.twitter.com/t0jf91VHHq"
, "pic.twitter.com/R5Cw7l6vnd"
, "pic.twitter.com/NiTXR6rMb8"
, "pic.twitter.com/Uis6iO6bxM"
, "pic.twitter.com/rSRiAIpVIS"
, "pic.twitter.com/LdcsxHkQJf"
, "pic.twitter.com/gzHNFf2pUQ"
, "pic.twitter.com/3nbLTvmFk4"
, "pic.twitter.com/wdwlN6Q4Yg"
, "pic.twitter.com/Ih30S5cwzp"
, "pic.twitter.com/w4pZ6O2k55"
, "pic.twitter.com/zGgyVv3kPa"
, "pic.twitter.com/33Ww1ln0iC"
, "pic.twitter.com/x2LhmmBYWO"
, "pic.twitter.com/SYG7V74i1E"
, "pic.twitter.com/VhZvs1xGxE"
, "pic.twitter.com/lmVvmlC2AR"
, "pic.twitter.com/Iylz5Ko5f1"
, "pic.twitter.com/Mqg53bMCh2"
, "pic.twitter.com/Hc9ts43mPA"
, "pic.twitter.com/TrZPVUTFUf"
, "pic.twitter.com/VQKaRI4F9s"
, "pic.twitter.com/UfiqvYu65u"
, "pic.twitter.com/80SdZNXayS"
, "pic.twitter.com/XbQWjgSPJX"
, "pic.twitter.com/Gj8KtoFEdm"
, "pic.twitter.com/wYo93ano77"
, "pic.twitter.com/WVnVdzaV61"
, "pic.twitter.com/GCj6r32BqH"
, "pic.twitter.com/a6TPBvjvUu"
, "pic.twitter.com/M0cpT6lQNd"
, "pic.twitter.com/iVENKMAPa3"
, "pic.twitter.com/UtDe9ibWLj"
, "pic.twitter.com/UPshq6YOU8"
, "pic.twitter.com/i3N2pjhRmc"
, "pic.twitter.com/H0dTRlnGHy"
, "pic.twitter.com/buQDM83g3X"
, "pic.twitter.com/9c3zWJc1kn"
, "pic.twitter.com/D5Cdha5plq"
, "pic.twitter.com/p4gwDqYeU0"
, "pic.twitter.com/TL4ekJCRQI"
, "pic.twitter.com/vp7aT0SIyH"
, "pic.twitter.com/lHQ8AYAM5k"
, "pic.twitter.com/HNHfXc4vWi"
, "pic.twitter.com/L5HF6Z546e"
, "pic.twitter.com/vT6HC1KEqL"
, "pic.twitter.com/3yKzo6pw0t"
, "pic.twitter.com/ckdsqb7Qxf"
, "pic.twitter.com/rTi92CbxXD"
, "pic.twitter.com/qQKGdgvo0k"
, "pic.twitter.com/hFKBFab8Gz"
, "pic.twitter.com/XGJSZpCZjl"
, "pic.twitter.com/Q2cAXn9isq"
, "pic.twitter.com/fHGxYadqhG"
, "pic.twitter.com/lB5oS9zzoH"
, "pic.twitter.com/4ifl5O6roA"
, "pic.twitter.com/0HsvyGkHuc"
, "pic.twitter.com/aUR1XwOwmz"
, "pic.twitter.com/zg03xFDXir"
, "pic.twitter.com/s09JlLVHEJ"
, "pic.twitter.com/QYypK7fC1J"
, "pic.twitter.com/CYHZOlEIdQ"
, "pic.twitter.com/2m5M74kbnv"
, "pic.twitter.com/GYBjRpycCD"
, "pic.twitter.com/iudGOPVxEu"
, "pic.twitter.com/PzJYnmKuFM"
, "pic.twitter.com/XhS9K08Zkr"
, "pic.twitter.com/D4Agy733aI"
, "pic.twitter.com/S9yJNNO2zZ"
, "pic.twitter.com/WRAPRolTah"
, "pic.twitter.com/kyWWBHi6yh"
, "pic.twitter.com/jA0bW2RDRs"
, "pic.twitter.com/8fOcDRqYo1"
, "pic.twitter.com/T5KJKgni8C"
, "pic.twitter.com/DHMJyPnTpE"
, "pic.twitter.com/mNRijJi3jz"
, "pic.twitter.com/WF4FTiKfXz"
, "pic.twitter.com/Gk5AIZVzZL"
, "pic.twitter.com/f5AvJbvWh5"
, "pic.twitter.com/u6N1z6zQZ4"
, "pic.twitter.com/ZGJoLq103y"
, "pic.twitter.com/eaWL01E6Sd"
, "pic.twitter.com/G874Gj7sMP"
, "pic.twitter.com/auKQ1TiCPY"
, "pic.twitter.com/C41BPmrQ1A"
, "pic.twitter.com/itGhdBf3NP"
, "pic.twitter.com/IsK5grZUwb"
, "pic.twitter.com/xGMSy5IkJd"
, "pic.twitter.com/l8WzuDfThu"
, "pic.twitter.com/mMifEc60t4"
, "pic.twitter.com/8UVdXUYTy4"
, "pic.twitter.com/WpMwrBlhpq"
, "pic.twitter.com/aawzNLItoH"
, "pic.twitter.com/9NANwbyTqD"
, "pic.twitter.com/Xfjltjr5BF"
, "pic.twitter.com/g85pwCYUqv"
, "pic.twitter.com/EsiH0O3RTx"
, "pic.twitter.com/bvRhR1p5Sg"
, "pic.twitter.com/MFVonw0SEZ"
, "pic.twitter.com/IuXeECiGTK"
, "pic.twitter.com/MYMcNFZJID"
, "pic.twitter.com/fBTr0aEU2z"
, "pic.twitter.com/2fZCjegcvY"
, "pic.twitter.com/WP8jzo9HC3"
, "pic.twitter.com/vjQyxau4Gp"
, "pic.twitter.com/CA2MJHQxPg"
, "pic.twitter.com/JKvoa1emS2"
, "pic.twitter.com/r3Q6JBb8hh"
, "pic.twitter.com/5GW2PUp9ib"
, "pic.twitter.com/x2Si7jChUw"
, "pic.twitter.com/cCbTPJrIYb"
, "pic.twitter.com/u6oTudR1mn"
, "pic.twitter.com/NVvGfIMyps"
, "pic.twitter.com/D75zV57N52"
, "pic.twitter.com/RmJQ50xJYf"
, "pic.twitter.com/dmD886XCrb"
, "pic.twitter.com/M7UQ3GXviA"
, "pic.twitter.com/g97hxHVI2k"
, "pic.twitter.com/BSlnj1Sn3o"
, "pic.twitter.com/uHViJ4XkBa"
, "pic.twitter.com/iTkkFnlvNv"
, "pic.twitter.com/irczqgfdbz"
, "pic.twitter.com/z6J7kObVUT"
, "pic.twitter.com/DpgNXmc18K"
, "pic.twitter.com/douk1G6VX8"
, "pic.twitter.com/YlYPIsbik4"
, "pic.twitter.com/zT3FDIBNAM"
, "pic.twitter.com/99Mevui3gL"
, "pic.twitter.com/H78hQHxbU6"
, "pic.twitter.com/t6jYx0BIt0"
, "pic.twitter.com/nFzxIyEkCo"
, "pic.twitter.com/X10apBEbZH"
, "pic.twitter.com/PyPwgfTKb4"
, "pic.twitter.com/ok3VSbsJDN"
, "pic.twitter.com/xuYyoiwq26"
, "pic.twitter.com/0gck8SwLzS"
, "pic.twitter.com/1QXezx9z3O"
, "pic.twitter.com/TeK00lhMmU"
, "pic.twitter.com/wA5NQkPZs3"
, "pic.twitter.com/yZFIF3OkMu"
, "pic.twitter.com/LbZw6oh6qM"
, "pic.twitter.com/9kikv3pjoz"
, "pic.twitter.com/SFTKG4LRiH"
, "pic.twitter.com/XXvQtZ52vj"
, "pic.twitter.com/pEthGvL7m8"
, "pic.twitter.com/tN5WF9i66l"
, "pic.twitter.com/6zkReDEExW"
, "pic.twitter.com/ZPCt2AYJUq"
, "pic.twitter.com/HhevPqJiO7"
, "pic.twitter.com/XnyaXMzcn1"
, "pic.twitter.com/99OizjXBOj"
, "pic.twitter.com/1V21MChuN7"
, "pic.twitter.com/aXW3aCqvz6"
, "pic.twitter.com/mtKpOjqiPY"
, "pic.twitter.com/ZlxwvvPYIF"
, "pic.twitter.com/jr1GQMXKRW"
, "pic.twitter.com/wXfdzgglzx"
, "pic.twitter.com/DrXYuc1svb"
, "pic.twitter.com/TItsnDvSb4"
, "pic.twitter.com/ANcWyn0yWW"
, "pic.twitter.com/rUn3dr1Yzr"
, "pic.twitter.com/EbABvwuDLB"
, "pic.twitter.com/SLygrfIlQX"
, "pic.twitter.com/5eU9htcWcw"
, "pic.twitter.com/MhvyXDejKc"
, "pic.twitter.com/X8wUFUzmpQ"
, "pic.twitter.com/8IDOx4GE69"
, "pic.twitter.com/V401AfqEYd"
, "pic.twitter.com/mQsIzH8NOk"
, "pic.twitter.com/zsyQyJ2FU3"
, "pic.twitter.com/D3zjkBR9WR"
, "pic.twitter.com/jcpXSCfE6N"
            , "pic.twitter.com/1GGjRfqabU"
, "pic.twitter.com/rNDVyuCAgL"
, "pic.twitter.com/WqQA0cwAVw"
, "pic.twitter.com/qj5czF7tGD"
, "pic.twitter.com/N8opYjyxAT"
, "pic.twitter.com/v6N1ix8pn0"
, "pic.twitter.com/Q3qjffVQM9"
, "pic.twitter.com/x9BQfLaRt8"
, "pic.twitter.com/dGo5zt3Qxx"
, "pic.twitter.com/vKb42JuoV1"
, "pic.twitter.com/8NlaVnpZB1"
, "pic.twitter.com/z66BpruVj7"
, "pic.twitter.com/hfbACeNmlk"
, "pic.twitter.com/UMP5OB5EG5"
, "pic.twitter.com/QYz8rOU3KS"
, "pic.twitter.com/e3LNFvlT7s"
, "pic.twitter.com/4Zrlm4KGmh"
, "pic.twitter.com/AdAPaBy5Rh"
, "pic.twitter.com/MDS63UT0Q0"
, "pic.twitter.com/8kmGDS28xI"
, "pic.twitter.com/V3iutOLmQM"
, "pic.twitter.com/UkaAWOThXi"
, "pic.twitter.com/IY2j7uXU12"
, "pic.twitter.com/ktnDkn8yps"
, "pic.twitter.com/N2Be2TJfRs"
, "pic.twitter.com/tAxeQYCqS2"
, "pic.twitter.com/cgMpgbdjYA"
, "pic.twitter.com/xW9OFb30kf"
, "pic.twitter.com/1dgHVvs6Oq"
, "pic.twitter.com/9Zznxd0z8F"
, "pic.twitter.com/BB4JHSr03F"
, "pic.twitter.com/XIfswcEJFX"
, "pic.twitter.com/XGtpYoi0j0"
, "pic.twitter.com/GVsDHCACvX"
, "pic.twitter.com/isa3vKhCIX"
, "pic.twitter.com/5Hq1uN737K"
, "pic.twitter.com/DRSudN9crY"
, "pic.twitter.com/OyZDMkSIK4"
, "pic.twitter.com/uQjugxPZjZ"
, "pic.twitter.com/1o7f7lN5Td"
, "pic.twitter.com/emICatuLSG"
, "pic.twitter.com/T6wHo7uWWv"
, "pic.twitter.com/6aT0GdCbHp"
, "pic.twitter.com/B2rLN1gYVy"
, "pic.twitter.com/hoQvIKLHb6"
, "pic.twitter.com/8HEodyIAes"
, "pic.twitter.com/b830FjyF1H"
, "pic.twitter.com/IOdE2PLXo8"
, "pic.twitter.com/HR5iMVVZ2m"
, "pic.twitter.com/RifYp1tBgx"
, "pic.twitter.com/ugY19B4ZOb"
, "pic.twitter.com/ETMy0X7dMi"
, "pic.twitter.com/vZPfwWxrkD"
, "pic.twitter.com/HoLIsaXxmx"
, "pic.twitter.com/z0kMbiktq5"
, "pic.twitter.com/CWlBd45miR"
, "pic.twitter.com/gRmlHCXzIG"
, "pic.twitter.com/oc2I8BMfWa"
, "pic.twitter.com/VgjzhpUMtg"
, "pic.twitter.com/8EBgbpm47v"
, "pic.twitter.com/TLKB3zNoja"
, "pic.twitter.com/hr6RV1fFLb"
, "pic.twitter.com/7h1vDG617W"
, "pic.twitter.com/sMaI0akECS"
, "pic.twitter.com/ChTyGCbvd7"
, "pic.twitter.com/plG7tq4tEq"
, "pic.twitter.com/a6ODU8WolS"
, "pic.twitter.com/eSe2QfgLWS"
, "pic.twitter.com/mvAp2gaAc8"
, "pic.twitter.com/le6qRfbzGl"
, "pic.twitter.com/LHqf8Wq2oe"
, "pic.twitter.com/lkI7DbOfOU"
, "pic.twitter.com/zTBCyAheDK"
, "pic.twitter.com/R78NrAkKh5"
, "pic.twitter.com/A0oUJWEQyj"
, "pic.twitter.com/0gCAPkFYcl"
, "pic.twitter.com/YD8wzsX08C"
, "pic.twitter.com/KTPCOCW7cL"
, "pic.twitter.com/E93pXzxqyl"
, "pic.twitter.com/oD3zeWaV8Q"
, "pic.twitter.com/yUs4ToXkRq"
, "pic.twitter.com/IoXsjg4FQB"
, "pic.twitter.com/Feq0unv5b1"
, "pic.twitter.com/xEK8Nb5BnU"
, "pic.twitter.com/zQMuIiij5Y"
, "pic.twitter.com/u9BItY0L2P"
, "pic.twitter.com/dM10zicQP9"
, "pic.twitter.com/nyC5pKxXn0"
, "pic.twitter.com/j4hYYRcwaZ"
, "pic.twitter.com/Fu5T5L7AnY"
, "pic.twitter.com/BYgNQxgrmr"
, "pic.twitter.com/gDMK41XcrI"
, "pic.twitter.com/7ebe7peZpA"
, "pic.twitter.com/eZzabj52Nm"
, "pic.twitter.com/kljyhPZnDA"
, "pic.twitter.com/DQPs3LA71o"
, "pic.twitter.com/68NayDliSd"
, "pic.twitter.com/EuZ6dqMLDq"
, "pic.twitter.com/BIMe358VNG"
, "pic.twitter.com/pEi4brA5iS"
, "pic.twitter.com/BfdztM2Vhr"
, "pic.twitter.com/RDGVRPRIeP"
, "pic.twitter.com/czcNKhvBEb"
, "pic.twitter.com/dnqMkcZKVj"
, "pic.twitter.com/yRF3yNS0BP"
, "pic.twitter.com/8PIBUemdAP"
, "pic.twitter.com/5qe1TuXLrz"
, "pic.twitter.com/YOPqTjWxTO"
, "pic.twitter.com/Xk1QkdnNce"
, "pic.twitter.com/pLaIwDDxAU"
, "pic.twitter.com/41NP0mXUot"
, "pic.twitter.com/iIguGki4uu"
, "pic.twitter.com/ZdPxvAGLFI"
, "pic.twitter.com/ixM7hSZPTS"
, "pic.twitter.com/gbYzK7FGmL"
, "pic.twitter.com/P4IAEDLFMy"
, "pic.twitter.com/Ghkqbi3Fr3"
, "pic.twitter.com/A4dPlKrzwV"
, "pic.twitter.com/s1PfqBnxpt"
, "pic.twitter.com/EaBA1E3iYf"
, "pic.twitter.com/cYWPvW3aW0"
, "pic.twitter.com/H3bBa9PMvY"
, "pic.twitter.com/4eBRmb68oF"
, "pic.twitter.com/biaMWijdW8"
, "pic.twitter.com/k6oWwlSFCU"
, "pic.twitter.com/4tdFJx3TcM"
, "pic.twitter.com/CFR9XimpIo"
, "pic.twitter.com/Ao2hdiw7Th"
, "pic.twitter.com/3heUPz7niR"
, "pic.twitter.com/JIghMrYHN0"
, "pic.twitter.com/krBaoPgv9w"
, "pic.twitter.com/N3AWqOxfQt"
, "pic.twitter.com/VCdTLL78Rw"
, "pic.twitter.com/UqH9SbGTxM"
, "pic.twitter.com/nYsLBNxDNK"
, "pic.twitter.com/CU6W6cdoxS"
, "pic.twitter.com/bh3Ku7AHRy"
, "pic.twitter.com/fBD4xoVnhP"
, "pic.twitter.com/C2HZM0ckSp"
, "pic.twitter.com/UY1HPuXWNy"
, "pic.twitter.com/nz0ye04yyl"
, "pic.twitter.com/ll9OlwAisP"
, "pic.twitter.com/1yU3rxuHXG"
, "pic.twitter.com/gCbuWtO8X5"
, "pic.twitter.com/vhPLheTBry"
, "pic.twitter.com/JJh2PR2VES"
, "pic.twitter.com/7EJaAlwkoG"
, "pic.twitter.com/UNAbmtlFwj"
, "pic.twitter.com/JhlBBwsMFX"
, "pic.twitter.com/sfl032WDro"
, "pic.twitter.com/1EFWMjW6kU"
, "pic.twitter.com/SKHO4knDkE"
, "pic.twitter.com/76j4YL5ivM"
, "pic.twitter.com/GjG3Bcq40n"
, "pic.twitter.com/YfpdEbMysL"
, "pic.twitter.com/lo8SQlsn0i"
, "pic.twitter.com/vPEEwd68jz"
, "pic.twitter.com/3OVIFyfI56"
, "pic.twitter.com/zzE8EdHLu1"
, "pic.twitter.com/4wbTbNVhpC"
, "pic.twitter.com/7u2cTDP2S0"
, "pic.twitter.com/Oyg6WOaEM0"
, "pic.twitter.com/gOCCBD6w8K"
, "pic.twitter.com/asRyJmshTE"
, "pic.twitter.com/dlhVeGtb7i"
, "pic.twitter.com/9GYWser02Z"
, "pic.twitter.com/lfP6qaqGrh"
, "pic.twitter.com/KI7zzDokpV"
, "pic.twitter.com/daXltm6Rw1"
, "pic.twitter.com/h8LRcOfsot"
, "pic.twitter.com/kSluOQ4kp2"
, "pic.twitter.com/kGQIZIq8uQ"
, "pic.twitter.com/0XBv0BU6eY"
, "pic.twitter.com/L3Mh3y2NHO"
, "pic.twitter.com/dCL9afuPsk"
, "pic.twitter.com/6DXy8ouxVv"
, "pic.twitter.com/NXgJpY43RL"
, "pic.twitter.com/sqbzKe3qvB"
, "pic.twitter.com/xyw0tgRdNT"
, "pic.twitter.com/J6UwdgjD9Q"
, "pic.twitter.com/9zLoxsoWi7"
, "pic.twitter.com/lAMLnew706"
, "pic.twitter.com/P75W1QmGdh"
, "pic.twitter.com/naqrVwGd57"
, "pic.twitter.com/nq9no3h2Eg"
, "pic.twitter.com/zdOBKwH5Xy"
, "pic.twitter.com/W0skvSTSBc"
, "pic.twitter.com/5VrzXz2nVU"
, "pic.twitter.com/GB2Fdf6Sfr"
, "pic.twitter.com/mCc5nxD52C"
, "pic.twitter.com/QMWdO95bYx"
, "pic.twitter.com/4RYFUqLtbK"
, "pic.twitter.com/LDD54QNEE7"
, "pic.twitter.com/xUIy9iCXKx"
, "pic.twitter.com/y67I6F9A6U"
, "pic.twitter.com/dBMMdvzV4A"
, "pic.twitter.com/MuZx6BcUsB"
, "pic.twitter.com/Hg4awZ1LtZ"
, "pic.twitter.com/qMKUfPhrQd"
, "pic.twitter.com/18VDH40Rsy"
, "pic.twitter.com/GXezak8QD2"
, "pic.twitter.com/8KxAZFwxDZ"
, "pic.twitter.com/zkLEVtrMl5"
, "pic.twitter.com/EgSbHuEy4C"
, "pic.twitter.com/CGtHY6Zzrq"
, "pic.twitter.com/INDbBDcrcj"
, "pic.twitter.com/5fbSpfdMuf"
, "pic.twitter.com/7hyltCTIcA"
, "pic.twitter.com/4zMVx2CFVI"
, "pic.twitter.com/aDZaMBGpl3"
, "pic.twitter.com/rldhkzpptI"
, "pic.twitter.com/BHwpqSKt5s"
, "pic.twitter.com/82jXXNxNeO"
, "pic.twitter.com/7ZpHK3ufGB"
, "pic.twitter.com/6pNRwNewDl"
, "pic.twitter.com/AFJMMebUaL"
, "pic.twitter.com/AQY28qET0q"
, "pic.twitter.com/UgRgDLyZA8"
, "pic.twitter.com/he1nizSDQE"
, "pic.twitter.com/tIoe9gby4J"
, "pic.twitter.com/8UCFiyYI6O"
, "pic.twitter.com/oxkkFoLDoJ"
, "pic.twitter.com/m0cleL336S"
, "pic.twitter.com/NJ29bMzzkr"
, "pic.twitter.com/1W2tuRe0VD"
, "pic.twitter.com/OLJ7pdyHPc"
, "pic.twitter.com/ZkLNSnNdAM"
, "pic.twitter.com/3WRgvMsyaS"
, "pic.twitter.com/EZ56Orb9tX"
, "pic.twitter.com/wCGWcJCXy6"
, "pic.twitter.com/sxsW3ms5br"
, "pic.twitter.com/qnk3IVa88H"
, "pic.twitter.com/hMXXpJh1Ag"
, "pic.twitter.com/6XXqbgcXD2"
, "pic.twitter.com/xROxfm3Qij"
, "pic.twitter.com/xy6MFohQtl"
, "pic.twitter.com/1tWfW2vozS"
, "pic.twitter.com/SA2TXg7nnS"
, "pic.twitter.com/ZlwwfD5Px5"
, "pic.twitter.com/6NX5i4WoKs"
, "pic.twitter.com/qt6UF1kOZL"
, "pic.twitter.com/5mMjiixM6Z"
, "pic.twitter.com/h7abtKYP0d"
, "pic.twitter.com/ia5u1Jl3EA"
, "pic.twitter.com/6G6xiUKfyh"
, "pic.twitter.com/Tikr3OqdYY"
, "pic.twitter.com/JomM0irzWy"
, "pic.twitter.com/PmnSHMyjsc"
, "pic.twitter.com/czBVmVwIDW"
, "pic.twitter.com/WmuCD6wYZ2"
, "pic.twitter.com/LuhbTF1U8W"
, "pic.twitter.com/iN16INC04V"
, "pic.twitter.com/hm9neKB8Jo"
, "pic.twitter.com/uaP47NZeGw"
, "pic.twitter.com/oAIliusKhk"
, "pic.twitter.com/VJGyqbxXmy"
, "pic.twitter.com/AxmQ8WwKyU"
, "pic.twitter.com/WFoWHyK3uE"
, "pic.twitter.com/XqbfgDWUo5"
, "pic.twitter.com/qaoXfHPdOo"
, "pic.twitter.com/481isgR7Qg"
, "pic.twitter.com/pm8qLoHn2j"
, "pic.twitter.com/LHXfcdvYBo"
, "pic.twitter.com/WlG1AfE6NK"
, "pic.twitter.com/mLGHXnRJ0f"
, "pic.twitter.com/tJ6ugz5KlE"
, "pic.twitter.com/PuiNCpjUIP"
, "pic.twitter.com/kXsXh4MUZx"
, "pic.twitter.com/MOoZXW1Abw"
, "pic.twitter.com/WwsItMslea"
, "pic.twitter.com/JRzdG0dALZ"
, "pic.twitter.com/l0zWSMKhSr"
, "pic.twitter.com/xyWIlG5FpA"
, "pic.twitter.com/r9BjUFhJxB"
, "pic.twitter.com/gn2tOgy30l"
, "pic.twitter.com/y1vrHw9uaH"
, "pic.twitter.com/2OLtENvsxK"
, "pic.twitter.com/XuKXz3eaVu"
, "pic.twitter.com/udtdKpZSQ6"
, "pic.twitter.com/6tEZ0Chnkz"
, "pic.twitter.com/TazqD9Aaga"
, "pic.twitter.com/BnmYxCT5np"
, "pic.twitter.com/CTpDFgeTkK"
, "pic.twitter.com/8mnFPaR7pH"
, "pic.twitter.com/8PTFiZcS9S"
, "pic.twitter.com/ODQqFWkQab"
, "pic.twitter.com/Xa9pkuVjGC"
, "pic.twitter.com/uNm2eKBmEm"
, "pic.twitter.com/VPAgcvkWZB"
, "pic.twitter.com/lEF8o8bf5O"
, "pic.twitter.com/LLLJhswOVP"
, "pic.twitter.com/Fb24uOMTsE"
, "pic.twitter.com/GNSvWNwoA6"
, "pic.twitter.com/5QOb3MYAXN"
, "pic.twitter.com/T9u0ztyRXD"
, "pic.twitter.com/PLtGLRdJSm"
, "pic.twitter.com/qUsv16DmXc"
, "pic.twitter.com/ZsndkkAsnw"
, "pic.twitter.com/xM7s0UfkDa"
, "pic.twitter.com/hqDh1Acqed"
, "pic.twitter.com/6PLk0PnaV0"
, "pic.twitter.com/2Y3Yd6X3dM"
, "pic.twitter.com/47fjok7YLs"
, "pic.twitter.com/ZG2odJW38e"
, "pic.twitter.com/g6bGfkLZBJ"
, "pic.twitter.com/UcWz9egk0K"
, "pic.twitter.com/immJljdqWq"
, "pic.twitter.com/vIaaL3kgro"
, "pic.twitter.com/aaQPJEFXmL"
, "pic.twitter.com/xI5fILwLfZ"
, "pic.twitter.com/uU4RLPjxge"
, "pic.twitter.com/aRr18Yarbs"
, "pic.twitter.com/ItzuwsAONj"
, "pic.twitter.com/ViC0fqWOKu"
, "pic.twitter.com/8uwbImst6b"
, "pic.twitter.com/GdfN3lfJDI"
, "pic.twitter.com/pQKKREnt2N"
, "pic.twitter.com/INGwjM0jC4"
, "pic.twitter.com/4bXa9O5XPY"
, "pic.twitter.com/B5iGp8eaE3"
, "pic.twitter.com/rPjEnaVUOV"
, "pic.twitter.com/gFxCeruKE1"
, "pic.twitter.com/6AJ8Rixrdg"
, "pic.twitter.com/jlXzv8rTCq"
, "pic.twitter.com/STXD2NVXpQ"
, "pic.twitter.com/Ynrj6yfJWm"
, "pic.twitter.com/Ycp7ao3bWS"
, "pic.twitter.com/7WtL5CodMO"
, "pic.twitter.com/0fb5vrZoc5"
, "pic.twitter.com/t8iOI3A6KT"
, "pic.twitter.com/AS79OSfPy0"
, "pic.twitter.com/XkbscjgTeQ"
, "pic.twitter.com/eq8RtYYKS6"
, "pic.twitter.com/mp2YmZw8fW"
, "pic.twitter.com/3g9giFhjSo"
, "pic.twitter.com/2ML2Kq3gfd"
, "pic.twitter.com/dqz48t9lMN"
, "pic.twitter.com/J29ugFOZya"
, "pic.twitter.com/DjRcIiaQzx"
, "pic.twitter.com/Q5xuRCmnUX"
, "pic.twitter.com/GMKKW2YpGZ"
, "pic.twitter.com/w3y0XCL4u9"
, "pic.twitter.com/kBlzIkxy0m"
, "pic.twitter.com/r2wDTnf9mW"
, "pic.twitter.com/zUT09q9r4o"
, "pic.twitter.com/HNp9rwZLJs"
, "pic.twitter.com/fnYGbQVXcQ"
, "pic.twitter.com/01Tt2KFRIc"
, "pic.twitter.com/JrbORsPnkz"
, "pic.twitter.com/2pR16QMXWT"
, "pic.twitter.com/50u7oB4wKS"
, "pic.twitter.com/HVlvU6E4xK"
, "pic.twitter.com/FgslyeZBS1"
, "pic.twitter.com/RmHxZaIXox"
, "pic.twitter.com/LQmsimB0v1"
, "pic.twitter.com/HbSqd1Hhhf"
, "pic.twitter.com/kPn6y1lLaP"
, "pic.twitter.com/nlFgV1fiAK"
, "pic.twitter.com/Nn2wfMBVVO"
, "pic.twitter.com/HQ8U9SJ6Wn"
, "pic.twitter.com/b8pMfSRqEG"
, "pic.twitter.com/qqIXoU9u0C"
, "pic.twitter.com/9WDWDAM2oD"
, "pic.twitter.com/MHaswhor1C"
, "pic.twitter.com/skul3SZKXd"
, "pic.twitter.com/nf2w5F5O2V"
, "pic.twitter.com/nThu1i6JQN"
, "pic.twitter.com/osDfFtgL2S"
, "pic.twitter.com/HS5GlOBPV2"
, "pic.twitter.com/rIpwYlUyvj"
, "pic.twitter.com/oQiLJxEEZ9"
, "pic.twitter.com/MrxaC11nxX"
, "pic.twitter.com/pop0rl5U9W"
, "pic.twitter.com/1uO1fJFH0o"
, "pic.twitter.com/1GIbgivog6"
, "pic.twitter.com/Ei7VE4pZxi"
, "pic.twitter.com/sXcBTcBAzy"
, "pic.twitter.com/pwPpGWkAg8"
    ];
        var num = Math.floor(Math.random() * twettear.length);
        $('.d').addClass('animated pulse infinite')
        $('.d').animate({
            'width': '70px'
            , 'height': '70px'
        }, 900000);
        window.setTimeout(function () {
            $('embed').remove();
            $('body').append('<embed src="Css/trino.wav" autostart="true" hidden="true" loop="false">');
            window.setTimeout(function () {
                window.location.reload(true);
            }, 3000);
        }, 900000);
        $('#Twitear').click(function () {
            var tweet = $('#texto').val();
            $('#texto').val('');
            window.open('http://www.twitter.com/share?text=' + tweet);
        })
        window.open('http://www.twitter.com/share?text=' + twettear[num]);
    })
    /*

    <script>
            $('document').ready(function () {
                var contenido = $('p a:contains("pic.twitter.com/")').text();

                alert(contenido.length);

                var twitte = ',"';
                for (var i = 0; i < contenido.length; i++) {


                    if (i % 26 == 0 && i != 0) {
                        twitte +=  '"' + "\n" + ',"';

                        if(contenido[i] != 'p' && contenido[i+1] != 'i' && contenido[i+2] != 'c'){
                        	while(contenido[i] != 'p' && contenido[i+1] != 'i' && contenido[i+2] != 'c'){
                        		i++;

                        	}
                        	break;
                        }
                    }
                    twitte += contenido[i];
                    if (i == contenido.length - 1) {
                        twitte += '"';
                    }
                }
                console.log(twitte);
            });
            
        </script>

    */