$(document).ready(function () {
    var twettear = [
        "Hay una fuerza motriz más poderosa que el vapor, la electricidad y la energía atómica: la voluntad"
        , "Primero tienes que aprender las reglas del juego, y después jugar mejor que nadie"
        , "El primer paso de la ignorancia es presumir de saber"
        , "El más poderoso hechizo para ser amado es amar."
        , "Errar es humano, pero más lo es culpar de ello a otros"
        , "El que confía sus secretos a otro hombre se hace esclavo de él"
        , "Dime y lo olvido, enséñame y lo recuerdo, involúcrame y lo aprendo"
        , "Quien tiene paciencia, obtendrá lo que desea"
        , "No malgastes tu tiempo, pues de esa materia está formada la vida"
        , "No cambies la salud por la riqueza, ni la libertad por el poder"
        , "Incluso la paz se puede comprar a un precio demasiado alto"
        , "Esta bien celebrar el éxito pero es más importante atender a las lecciones del fracaso."
        , "El éxito es un mal maestro."
        , "Seduce a la gente inteligente a pensar que no pueden perder."
        , "Todo hombre tiene derecho a decidir su propio destino"
        , "No te preocupes por una cosa, concéntrate en que las pequeñas cosas salgan bien."
        , "Nadie excepto nosotros mismos puede liberar nuestra mente."
        , "Si te sientes deprimido todos los días, estas diciendo oraciones al diablo."
        , "La salud es el regalo más grande, la satisfacción de la mayor riqueza, la fidelidad de la mejor relación."
        , "A un loco se le conoce por sus actos, a un sabio también."
        , "Cuida el exterior tanto como el interior; porque todo es uno."
        , "La reflexión es el camino hacia la inmortalidad; la falta de reflexión, el camino hacia la muerte"
        , "No insistas en el pasado, no sueñes en el futuro, concentra tu mente en el momento presente."
        , "La verdad se corrompe tanto con la mentira como con el silencio."
        , "Los hombres son como los vinos: la edad agria los malos y mejora los buenos."
        , "Cuanto mayor es la dificultad, mayor es la gloria."
        , "A pesar de que ya soy mayor, sigo aprendiendo de mis discípulos."
        , "Mi conciencia tiene en mí más peso que la opinión de todo el mundo."
        , "Exígete mucho a ti mismo y espera poco de los demás. Así te ahorrarás disgustos."
        , "Cada cosa tiene su belleza, pero no todos pueden verla."
        , "Donde hay educación no hay distinción de clases."
        , "Estudia el pasado si quieres predecir el futuro."
        , "El hombre que ha cometido un error y no lo corrige comete otro error mayor."
        , "Nadie te puede hacer sentir inferior sin tu consentimiento."
        , "Las grandes mentes discuten las ideas; las mentes promedio discuten los acontecimientos; las mentes pequeñas discuten con las personas."
        , "La confianza en sí mismo es el primer secreto del éxito."
        , "Grabad esto en vuestro corazón: cada día es el mejor del año."
        , "Todo hombre es sincero a solas; en cuanto aparece una segunda persona empieza la hipocresía."
        , "Un amigo es una persona con la que se puede pensar en voz alta."
        , "Los años enseñan muchas cosas que los días jamás llegan a conocer."
        , "La amistad duplica las alegrías y divide las angustias por la mitad."
        , "Vengándose, uno se iguala a su enemigo; perdonándolo, se muestra superior a él."
        , "La ocasión hay que crearla, no esperar a que llegue."
        , "Un hombre está dispuesto a creer aquello que le gustaría que fuera cierto."
        , "Lo que me preocupa no es que me hayas mentido, sino que, de ahora en adelante, y no podré creer en ti."
        , "La madurez del hombre es haber vuelto a encontrar la seriedad con la que jugaba cuando era niño."
        , "El destino de los hombres no está hecho de momentos felices, toda la vida los tiene, sino no de épocas felices."
        , "Ser independiente es cosa de una pequeña minoría, es el privilegio de los fuertes."
        , "Lo que no me mata, me hace más fuerte."
        , "En la vida no se trata de encontrarse uno mismo, sino de crearse uno mísmo."
        , "Dad al hombre salud y metas a alcanzar y no se detendrá a pensar sobre si es o no feliz."
        , "El miedo puede llevar a los hombres a cualquier extremo."
        , "Lo peor que puede pasarle aun hombre es llegar a pensar mal de sí mismo."
        , "No basta saber, se debe también aplicar. No es suficiente querer, se debe también hacer."
        , "El amor y el deseo son las alas del espíritu de las grandes hazañas."
        , "Muchos hombres no se equivocan jamás porque no se proponen nada razonable."
        , "Cuando el hombre no se encuentra a sí mismo, no encuentra nada."
        , "Hay una forma de saber si un hombre es honesto; pregúntaselo.Si dice que si, sabrás que es un sinverguenza."
        , "A parte del perro, un libro es el mejor amigo del hombre. Dentro de un perro esta demasiado oscuro para leer."
        , "El fracaso es simplemente una nueva oportunidad de empezar de nuevo, esta vez de forma más inteligente."
        , "No hay hombre vivo que no pueda hacer más de lo que el piensa que puede hacer."
        , "Los obstáculos son las cosas horribles que ves al apartar tus ojos de tu meta."
        , "Pensar es el trabajo más duro que hay, quizás por eso tan pocos se dedican a ello."
        , "La vida es lo que pasa mientras estas ocupado haciendo otros planes."
        , "La realidad deja mucho a la imaginación."
        , "Uno nunca tiene miedo de lo desconocido; uno tiene miedo de lo conocido llegando a un fin."
        , "La medida de la salud no es estar adaptado a una sociedad profundamente enferma."
        , "La habilidad de observar sin evaluar es la forma más alta de inteligencia."
        , "Dime a qué prestas atención y te diré quien eres."
        , "He cometido el peor pecado que uno puede cometer. No he sido feliz."
        , "Hay que tener cuidado al elegir a los enemigos porque uno termina pareciéndose a ellos."
        , "La duda es uno de los nombres de la inteligencia."
        , "Hay derrotas que tienen más dignidad que la victoria."
         , "Uno no es lo que es por lo que escribe, sino por lo que ha leído."
         , "Vive como si fueras a morir mañana, aprende como si fueras a vivir para siempre."
        , "El débil nunca puede olvidar. Olvidar es un atributo del fuerte."
        , "Nadie me puede hacer daño sin mi permiso."
        , "La fuerza no viene de una capacidad física. Viene de una voluntad indomable."
        , "La felicidad es cuando lo que piensas, dices y haces están en harmonía."
        , "La violencia es el último refugio del incompetente."
        , "La vida es agradable. La muerte es pacífica. Es la transición la que es problemática."
        , "La suerte favorece solo a la mente preparada."
        , "Nunca dejes que tu sentido de la moralidad se interponga en el camino de hacer lo que es correcto."
        , "La simplicidad es la última sofisticación."
        , "Las decepciones más grandes que el hombre sufre son por sus propias opiniones."
        , "No puedes tener mayor dominio que sobre ti mismo."
        , "Al igual que el coraje pone en peligro la vida, el miedo la protege."
        , "Todo el mundo piensa en cambiar el mundo, pero nadie piensa en cambiarse a si mismo."
        , "Si hablas a un hombre en un idioma que entiende, llegarás a su cabeza. Si le hablas en su idioma, llegará a su corazón."
        , "Siempre parece imposible hasta que se realiza."
        , "Una buena cabeza y un buen corazón son siempre combinaciones formidables."
        , "La mejor venganza es ser diferente a quien causó el daño."
        , "Tienes poder en tu mente, no afuera. Se consciente de esto y encontrarás las fuerza."
        , "Cuando te encuentres a ti mismo al lado de la mayoría, es tiempo de parar y reflexionar."
        , "A nadie le va mal durante mucho tiempo sin que él mismo tenga la culpa."
        , "El que no esté seguro de su memoria debe abstenerse de mentir."
        , "El signo más cierto de la sabiduría es la serenidad constante."
        , "El hombre sabio no lo es en todas las cosas."
        , "No hay cosa de la que tenga tanto miedo como del miedo."
        , "La senda de la virtud es muy estrecha y el camino del vicio, ancho y espacioso."
        , "El que lee mucho y anda mucho, ve mucho y sabe mucho."
        , "Amistades que son ciertas nadie las puede turbar."
        , "Donde una puerta se cierra, otra se abre."
        , "Sea moderado tu sueño; que el que no madruga con el sol, no goza del día."
        , "La envidia es una declaración de inferioridad."
        , "Los sabios son los que buscan la sabiduría; los necios piensan haberla encontrado."
        , "El coraje no se puede simular: es una virtud que escapa a la hipocresía."
        , "Si no puedes hacer grandes cosas, haz pequeñas cosas de una forma grande."
        , "Piensa dos veces antes de hablar, porque tus palabras e influencia plantarán la semilla del éxito o fracaso en la mente del otro."
        , "El hombre que hace más de lo que se le paga, pronto se le pagará más de loque hace."
        , "A veces podemos pasarnos años sin vivir en absoluto, y de pronto toda nuestra vida se concentra en un solo instante."
        , "La única ventaja de jugar con fuego es que aprende uno a no quemarse."
        , "Que hablen de uno es espantoso. Pero hay algo peor: que no hablen."
        , "Las preguntas no son nunca indiscretas. Las respuestas, a veces sí."
        , "La pregunta real no es si la vida existe antes de la muerte. La pregunta real es si estas vivo antes de la muerte."
        , "La juventud no tiene edad."
        , "El que piensa que puede, puede. El que piensa que no puede, no puede. Esa es una inexorable e indiscutible ley."
        , "Toma mucho tiempo llegar a ser jóven."
        , "La mayor declaración de amor es la que no se hace; el hombre que siente mucho, habla poco."
        , "La libertad está en ser dueños de nuestra propia vida."
        , "Buscando el bien de nuestros semejantes, encontramos el nuestro."
        , "Cada minuto que estas cabreado pierdes sesenta segundos de felicidad."
        , "La paciencia es amarga, pero sus frutos son dulces."
        , "La juventud es el momento de estudiar la sabiduría; la vejez, el de practicarla."
        , "Si la razón hace al hombre, el sentimiento lo conduce."
        , "Siempre es más valioso tener el respeto que la admiración de las personas."
        , "Nadie puede ser feliz si no se aprecia a sí mismo."
        , "Importa mucho más lo que tú piensas de ti mismo que lo que los otros opinen de ti."
        , "Si quieres que tu secreto sea guardado, guárdalo tú mismo."
        , "No es pobre el que tiene poco, sino el que mucho desea."
        , "El lenguaje de la verdad debe ser, sin duda alguna, simple y sin artificios."
        , "La recompensa de una buena acción está en haberla hecho."
        , "La inteligencia es la habilidad de adaptarse al cambio."
        , "El trabajo te da significado y propósito y la vida esta vacía sin el."
        , "Puede ser un héroe el que triunfa y el que sucumbe, pero jamás el que abandona el combate."
        , "Para disipar una duda, cualquiera que sea, se necesita una acción."
        , "Siempre hay un lugar en las cumbres para el hombre valiente y que se esfuerza."
        , "El hablar que no termina en acción, mejor suprimirlo."
        , "Sólo en un mundo de hombres sinceros es posible la unión."
        , "Si hiciéramos las cosas de las que somos capaces, nos sorprenderíamos a nosotros literalmente."
        , "Los cuarenta son la edad madura de la juventud; los cincuenta la juventud de la edad madura."
        , "La melancolía es la felicidad de estar triste."
        , "Atreveos: el progreso solamente se logra así."
        , "A nadie le faltan fuerzas; lo que a muchísimos les falta es voluntad."
        , "El sufrir merece respeto, el someterse es despreciable."
        , "Las que conducen y arrastran al mundo no son las máquinas, sino las ideas."
        , "Sólo es inmensamente rico aquel que sabe limitar sus deseos."
        , "El verdadero valor consiste en saber sufrir."
        , "Ser bueno solamente consigo mismo es ser bueno para nada."
        , "Quienes creen que el dinero lo hace todo, terminan haciendo todo por dinero."
        , "Decimos una necedad y a fuerza de repetirla acabamos creyéndola."
        , "Cuanto más te gustas a ti mismo, menos te pareces a los demás, lo que te hace único."
        , "El modo de empezar es dejar de hablar y comenzar a hacer."
        , "Hay más tesoros en los libros que en todo el botín pirata de la isla del tesoro."
        , "Cuando eres curioso, encuentras muchas cosas interesantes que hacer."
        , "El riesgo viene de no saber qué estas haciendo."
        , "Solo compra cosas con las que estarías feliz si el mercado cerrase durante 10 años."
        , "Si cambias el modo en que miras las cosas, las cosas que miras cambian."
        , "Si no recuerdas la más ligera locura en que el amor te hizo caer, no has amado."
        , "Un hombre que no se alimenta de sus sueños envejece pronto."
        , "El destino es el que baraja las cartas, pero nosotros somos los que jugamos."
        , "No tratéis de guiar al que pretende elegir por sí su propio camino."
        , "Es mejor ser rey de tu silencio que esclavo de tus palabras."
        , "Una broma es algo muy serio."
        , "La actitud es una pequeña cosa que hace una gran diferencia."
        , "El precio de la grandeza es la responsabilidad."
        , "Hagas lo que hagas, bueno o malo, la gente siempre tendrá algo que decir."
        , "Llega el momento en que hay que darse cuenta que algunas personas pueden quedarse en nuestro corazón, pero no en nuestra vida."
        , " Hazlo ahora. A veces“ después” se convierte en“ nunca”."
        , "Demasiado ego matará a tu talento."
        , "La vida no es un problema a ser resuelto, sino una realidad a ser experimetada."
        , "La vida es realmente simple, pero insistimos en hacerla complicada."
        , "No recordamos días, recordamos momentos."
        , "Al final, no cuentan los años de tu vida.Cuenta la vida en tu años."
        , "Solo vives una vez, pero si lo haces bien, una vez es suficiente."
        , "La cosa más importante de la vida es disfrutarla, ser feliz, es todo lo que importa."
        , "El propósito de nuestra vida es ser feliz."
        , "La buena vida es inspirada por amor y guiada por el conocimiento."
        , "La vida es como montar en bicicleta.Para mantener el equilibrio debes seguir adelante."
        , "La vida es inherentemente arriesgada Solo hay un riesgo mayor que deberías evitar, y es el riesgo de no hacer nada."
    ];
    var num = Math.floor(Math.random() * twettear.length);
    $('.d').animate({
        'width': '0px'
        , 'height': '0px'
    }, 900000);
    window.setTimeout(function () {
        $('embed').remove();
        $('body').append('<embed src="Css/trino.wav" autostart="true" hidden="true" loop="false">');
        window.setTimeout(function () {
            window.location.reload(true);
        }, 3000);
    }, 900000);
    $('#Twitear').click(function () {
        var tweet = $('#texto').val();
        $('#texto').val('');
        window.open('http://www.twitter.com/share?text=' + tweet);
    })
    window.open('http://www.twitter.com/share?text=' + twettear[num]);
})